name: Run Code Redeem Script

on:
  schedule:
    - cron: "0 0 * * *" # Run every day at 12 AM
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      # PUPPETEER_EXECUTABLE_PATH: /usr/bin/google-chrome-stable
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
      NODE_ENV: production
      GENSHIN_EMAIL : ${{ secrets.GENSHIN_EMAIL }}
      GENSHIN_PASSWORD : ${{ secrets.GENSHIN_PASSWORD }}
      GENSHIN_SERVER: ${{ secrets.GENSHIN_SERVER }}

    defaults:
      run:
        working-directory: ./scripts

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.17.1"

      - name: Set up Chrome
        id: setup-chrome
        uses: browser-actions/setup-chrome@latest

      - name: Print Chrome Version
        run: |
          echo "Chrome version from PATH:" chrome --version
          echo "Chrome path"
          echo "${{ steps.setup-chrome.outputs.chrome-path }}" --version

      # - name: Print Environment Variables
      #   run: printenv

      - name: Install Dependencies
        run: npm ci

      - name: Run Redeem Script
        run: npm run check-codes

      - name: Format Available Codes JSON File
        run: npm run format

      - name: Commit availableCodes.json
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          if git diff-index --quiet HEAD -- src/constants/availableCodes.json; then
            echo "No changes detected. Skipping commit."
            exit 0
          else
            git add src/constants/availableCodes.json
            git commit -m "Format availableCodes.json"
            git push
          fi
